version: '3'
services:
  mariadb:
    image: redis
    container_name: urlDB
    hostname: redisUrl
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning --requirepass ${PASSWORD}
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local